data:
  train_urls:
    - "gs://mimir-data-eu/mimir-core/data/train-bad-{0001..0006}-of-0006.json.gz"
    - "gs://mimir-data-eu/mimir-core/data/train-medium-{0001..0021}-of-0021.json.gz"
    - "gs://mimir-data-eu/mimir-core/data/train-good-{0001..0007}-of-0007.json.gz"
  validation_urls:
    - "gs://mimir-data-eu/mimir-core/data/validation-bad-0001-of-0001.json.gz"
    - "gs://mimir-data-eu/mimir-core/data/validation-medium-0001-of-0001.json.gz"
    - "gs://mimir-data-eu/mimir-core/data/validation-good-0001-of-0001.json.gz"
  cache_dir: "gs://mimir-train-us/levanter/tokenized/mimir-core"
  tokenizer: "mistralai/Mistral-7B-v0.1"
model:
  type: mistral

  seq_len: 2048
  hidden_dim: 4096
  intermediate_dim: 14336
  num_layers: 32
  num_heads: 32
  num_kv_heads: 8
  sliding_window: 2048

  activation_function: silu
  initializer_range: 0.02
  layer_norm_epsilon: 1e-05
  
  # upcast_attn: false
  use_flash_attention: true
  attn_backend: JAX_FLASH
  flash_attention_block_size: 1024
  # gradient_checkpointing: true
  # gradient_checkpointing_block_size: 5
  scan_layers: true
  # use_bias: false
  # rope_scaling: null
initialize_from_hf: "mistralai/Mistral-7B-v0.1"
use_hf_model_config: false
trainer:
  wandb:
    entity: "nbailab"
    project: "Mímir Levanter - mimir-mistral-7b-core"
    name: mimir-mistral-7b-core
    tags: ["mistral", "core", "7B", "warm"]

  mp: p=f32,c=bfloat16
  train_batch_size: 2048  # Set to 2048 and parallelism 16, grad acc adjusted so 2048*2048=4194304, maybe 2040 here and 30 per_device  # 256 set for v4-64 TPU
  per_device_parallelism: 32  # anything smaller than 128 will trigger grad acc, but 128 won't fit in memory, so we decrease it
  per_device_eval_parallelism: 32
  num_train_steps: 64000
  steps_per_eval: 1000
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"

  checkpointer:
    base_path: "gs://mimir-train-us/levanter/mimir-mistral-7b-core/checkpoints"
    save_interval: 1h
    keep:
      - every: 1000

optimizer:
  lr_schedule: cosine
  learning_rate: 3E-04
  beta1: 0.9
  beta2: 0.95
  epsilon: 1e-8
  weight_decay: 0.1
  warmup: 0.03125  # ~2000 steps
  min_lr_ratio: 0.1  # end lr 3E-05

hf_save_steps: 10000
hf_save_path: "gs://mimir-train-us/levanter/mimir-mistral-7b-core/hf"
hf_upload: NbAiLab/mimir-mistral-7b-core
